### ISSUE TITLE
vignette-js API using chaining

### ISSUE THREAD

**Issue by kvas-damian** [Wikia/vignette-js#19]
```Vignette.getThumbURL``` already takes 5 params. Some of them probably could be optional, that's why I'm thinking how to make it simpler and more readable.

What do you think about changing API to pass optional params in separate methods. The same way as we're doing it on  backend side: 
https://github.com/Wikia/app/blob/dev/extensions/wikia/ImageServing/imageServing.class.php#L315
````
VignetteRequest::fromFile($image)
->windowCrop()
->width($this->width)
->xOffset($left)
->yOffset($top)
->windowWidth($right - $left)
->windowHeight($bottom - $top)
->url();
````

This is just suggestion. It'd be great if we could start discussion here.

**Comment by mklucsarits** [comment]
The latest release addresses this issue with a new format for getThumbURL.

**Comment by kvas-damian** [comment]
:+1:
